version: '3.7'

services:
  origin:
    build: .
    ports:
    - "2352:2352/tcp"
    # environment:
    networks:
      myipvlan:
        ipv4_address: 192.168.0.4

networks:
  myipvlan:
    external: true
    name: br0